### ISSUE TITLE
Doesn't start on fedora

### ISSUE THREAD

**Issue by sannagy90** [it-is-wednesday/cute-sway-recorder#26]
I'm getting the following error on starting this app

```
cute-sway-recorder 
Traceback (most recent call last):
  File "/home/madeupuser/.local/bin/cute-sway-recorder", line 5, in <module>
    from cute_sway_recorder.main import main
  File "/home/madeupuser/.local/pipx/venvs/cute-sway-recorder/lib64/python3.10/site-packages/cute_sway_recorder/main.py", line 24, in <module>
    from config_area import ConfigArea
```

Fedora 36 with latest sway

**Comment by it-is-wednesday** [comment]
Thanks for the catch! I uploaded a new version with a fix. Can you run `pip install -U cute-sway-recorder` and see if it helps?

**Comment by sannagy90** [comment]
works fine now, thank you!
I wonder if you have any plans adding a feature that would make it possible to pick an audio source.
You can do that with -a using wf-recorder and I think it would be a great addition.

**Comment by it-is-wednesday** [comment]
Yeah, there is, but you're always welcome to open a PR! Or wait until I get some extra time in my hands;)
