### ISSUE TITLE
Need flag `--force-yuv` or else all recorded videos not playable

### ISSUE THREAD

**Issue by kohane27** [it-is-wednesday/cute-sway-recorder#28]
Hello @it-is-wednesday. Hope you're doing well. Thank you for creating this graphical wrapper. It makes using `wf-recorder` a lot easier.

## Description

I had the exact same issue mentioned in [#152](https://github.com/ammen99/wf-recorder/issues/152). All the videos recorded with `cute-sway-recorder` aren't playable when shared on uploaded. They are playable locally with `mpv`. 

## Solution

The solution is adding the flag `--force-yuv`:

```
-t, --force-yuv
Use the -t or --force-yuv option to force conversion of the data to yuv format, before sending it to the gpu.
```

## Problem

Given `cute-sway-recorder` uses `wf-recorder` under the hood, it's solvable by adding the flag `--force-yuv`. But there's no easy way to add flags. Currently, I have to modify the src code:

1. `cd ~/.local/pipx/venvs/cute-sway-recorder/lib/python3.10/site-packages/cute_sway_recorder/main.py`

2. add `--force-yuv` to params like below:

```
params = ["wf-recorder", "-f", file_dst, "--force-yuv"]
```

## Suggestion

Add an input box under `Record audio` so that users can pass flags.

Thank you!

**Comment by it-is-wednesday** [comment]
Oh shit thanks for the detailed issue! I really appreciate the effort <3

Adding such a box is a great solution, I'll definitely add it when I get back on my Linux machine. If you would like to submit a PR yourself I'd obviously greatly appreciate that;) But no rush at all

**Comment by it-is-wednesday** [comment]
Woah, wait, how does that work? I didn't know you can just append random flags to `env`. Can you please explain? I'm curious how it works and can't find anything online and in `env`'s manual!
