### ISSUE TITLE
Persistent configuration

### ISSUE THREAD

**Issue by ketexon** [it-is-wednesday/cute-sway-recorder#35]
In this PR https://github.com/it-is-wednesday/cute-sway-recorder/issues/33#issuecomment-2094851170 there was mention of setting defaults in a config file in `~/.config/cute-sway-recorder/defaults.{ext}`
It was mentioned that it should use [`configparser`](https://docs.python.org/3.7/library/configparser.html) or [`tomllib`](https://docs.python.org/3.11/library/tomllib.html) (which only supports >3.11)

**Comment by ketexon** [comment]
I wanted to start working on this if @kohane27 hasn't already, and wanted to ask:

- Is `configparser` preferred since it supports 3.7?
- Is `defaults.conf` good for a filename?

Also I'm thinking that parsing should be done in  the `__init__` function of `ConfigArea` and passed to `FileDestGroup`, though lmk if there's a better way.

**Comment by kohane27** [comment]
Hello @ketexon thank you for helping out! I haven't yet started working on it so pr is very much welcome :heart: 

> Is configparser preferred since it supports 3.7?

Yes, as discussed in #33

> Is defaults.conf good for a filename?

I think so

Please tag me when it's done we can test it together! Thank you again!

**Comment by it-is-wednesday** [comment]
Let's move the discussion to #37, thanks for all the effort gentlemen <3
